---
title: "Week 5, Day 1"
author: "Sasha Paulovich"
date: "July 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Cross-checking our recorded morning commutes with MTA data

```{r libs, message=FALSE}
library(tidyverse)
```

#### Get subway data and station names
```{r load-data}
# checking the 1 train
subway <- read_csv('feed_1_20180709_to_20180710.csv')
stations <- read_csv('http://web.mta.info/developers/data/nyct/subway/Stations.csv')

commutes <- read_csv('commutes.csv')
```

#### Combine dataframes and add human-readable timestamps
```{r combine-dfs}

station_names <- stations %>%
  select(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`) %>%
  mutate(stop_id_south = sprintf("%sS", stop_id)) 


subway_1 <- subway %>% 
  mutate(min_time = as.POSIXct(minimum_time, origin = "1970-01-01", tz="America/New_York"), 
         max_time = as.POSIXct(maximum_time, origin = "1970-01-01", tz="America/New_York"),
         latest_time = as.POSIXct(latest_information_time, origin = "1970-01-01", tz="America/New_York"))


filtered_data <- left_join(subway_1, station_names, by=c("stop_id"="stop_id_south"))

```


#### Trip details
**trip_id** = 055800_1..S03R  
**start location** = 127S (Times Sq - 42 St)  
**end location** = 131S (18 St)
```{r filter}
my_trip <- filtered_data %>% 
  filter(route_id == "1", action == "STOPPED_AT", trip_id == "055800_1..S03R", 
         stop_id.y >= 127, stop_id.y <= 131)

as.data.frame(my_trip)
```




